conf11:
  effective_cache_size: 22830213kB
  geqo_selection_bias: 1.76
  maintenance_work_mem: 728894kB
  max_wal_size: 5825MB
  random_page_cost: 332.17
  work_mem: 576345kB
  enable_nestloop: off
  full_page_writes: on
  plan_cache_mode: force_generic_plan
  commit_delay: 188
  shared_buffers: 586079
  wal_buffers: 14943
conf15:
  effective_cache_size: 12239362kB
  geqo_selection_bias: 1.89
  maintenance_work_mem: 5255628kB
  max_wal_size: 8342MB
  random_page_cost: 163.45
  work_mem: 1125508kB
  enable_nestloop: on
  full_page_writes: on
  plan_cache_mode: auto
  commit_delay: 3539
  shared_buffers: 132584
  wal_buffers: 16254
