conf4:
  effective_cache_size: 21143671kB
  geqo_selection_bias: 1.91
  maintenance_work_mem: 158472kB
  max_wal_size: 6528MB
  random_page_cost: 61.76
  work_mem: 427549kB
  enable_nestloop: on
  full_page_writes: off
  plan_cache_mode: force_custom_plan
  commit_delay: 3110
  shared_buffers: 615259
  wal_buffers: 2777
conf6:
  effective_cache_size: 19499229kB
  geqo_selection_bias: 1.76
  maintenance_work_mem: 569110kB
  max_wal_size: 6845MB
  random_page_cost: 241.35
  work_mem: 237964kB
  enable_nestloop: on
  full_page_writes: off
  plan_cache_mode: auto
  commit_delay: 678
  shared_buffers: 489920
  wal_buffers: 6476
  